"""file_index table

Revision ID: cefb05d41155
Revises:
Create Date: 2024-02-19 01:35:12.604809

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cefb05d41155"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_index",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_path", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("vector_store_id", sa.String(), nullable=False),
        sa.Column("vector_store_name", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_index")
    # ### end Alembic commands ###
